# Generated by Django 2.2 on 2021-02-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20210225_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseitem',
            old_name='expenses',
            new_name='user_profile',
        ),
    ]
